global using FinancialApplication.Data;
global using FinancialApplication.Models;
global using FinancialApplication.Service.Contract;
global using Microsoft.EntityFrameworkCore;
global using FinancialApplication.DTO;
global using Microsoft.Extensions.Configuration;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using FinancialApplication.Commons;