global using FinancialApplication.Data;
global using FinancialApplication.Extensions;
global using FinancialApplication.Models;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using FinancialApplication.Helpers;
global using FinancialApplication.DTO;
global using FinancialApplication.Service.Contract;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using System.IdentityModel.Tokens.Jwt;
global using static FinancialApplication.Helpers.ApiRoutes;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Diagnostics;
global using System.Net;